services:
  gigaam-transcriber:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./hf_cache/:/root/.cache
    env_file:
      - .env
    command: ["data/input.mkv"]
    network_mode: "host"

volumes:
  data_cache: