services:
  gigaam-transcriber:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./hf_cache/:/root/.cache
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python3", "-u", "main.py", "data/input.mkv"]
    network_mode: "host"

volumes:
  data_cache: